### ISSUE TITLE
Issue with build macro

### ISSUE THREAD

**Issue by arthmis** [microsoft/winrt-rs#364]
I'm using the latest version of winrt-rs as of today and the build macro isn't working in `build.rs`. I'm using it like so:
```rust
fn main() {
    winrt::build!(
        dependencies
            os
            nuget: Microsoft.Windows.Toolkit.Uwp
        types
            windows::data::xml::dom::*
            windows::ui::notifications::*
            microsoft::windows::toolkit::uwp::*
    );
}
```
My `Cargo.toml` looks like:
```toml
[dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs"}

[build-dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs" }

[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.17763.1000"
"Microsoft.Toolkit.Uwp.Notifications" = "6.1.1"
```
I've installed cargo winrt. I've installed the nuget packages first and only use `cargo winrt build`. When I run that command I get the error 
```bash
error: expected `types`
 --> build.rs:3:9
  |
3 |         dependencies
  |         ^^^^^^^^^^^^

error: aborting due to previous error
```
I haven't included the `main.rs` code because I can't get past the build step. I'm following the documentation generated from rustdoc so it should be the latest documentation.

I'm using that `SDK` version because that's the latest I have. Is it required that I have the latest Windows 10 SDK which is `10.0.19041.0` like in the examples?
